New Button by Figma
platformbuilders/fluid-react pull request #167
Opened 2023-12-12 21:07 UTC by mdlucas

## O que foi feito? 📝

Implementação do botão de acordo com o Figma usado pelos Designers
## Screenshots ou GIFs 📸

![Captura de Tela 2023-12-12 às 17 34 52](https://github.com/platformbuilders/fluid-react/assets/6132299/1660eae7-0eca-46d6-8409-89dd07f811b6)
![Captura de Tela 2023-12-12 às 17 35 06](https://github.com/platformbuilders/fluid-react/assets/6132299/3f150e5e-5957-48d4-92a2-bbf718826050)
![Captura de Tela 2023-12-12 às 17 35 21](https://github.com/platformbuilders/fluid-react/assets/6132299/5668ea53-6e80-4a4d-9ccf-a1e60e822ec7)
![Captura de Tela 2023-12-12 às 17 35 36](https://github.com/platformbuilders/fluid-react/assets/6132299/023b1e75-d49b-4bd6-b3f9-5a095fcb520e)
![Captura de Tela 2023-12-12 às 17 35 48](https://github.com/platformbuilders/fluid-react/assets/6132299/e3f2e9db-f975-4eb3-864b-ebab820ef73b)
![Captura de Tela 2023-12-12 às 17 35 56](https://github.com/platformbuilders/fluid-react/assets/6132299/e1fec076-d3af-40f8-a59d-99a404967331)
![Captura de Tela 2023-12-12 às 17 46 10](https://github.com/platformbuilders/fluid-react/assets/6132299/9f021223-9e3c-4026-9f6a-8f884ff46cd7)
![Captura de Tela 2023-12-12 às 17 46 13](https://github.com/platformbuilders/fluid-react/assets/6132299/d6f162c8-26ba-4b0b-a7df-3471a8525efc)
![Captura de Tela 2023-12-12 às 17 46 21](https://github.com/platformbuilders/fluid-react/assets/6132299/03d6185a-ad92-403f-a698-d9765ffd0e9e)
![Captura de Tela 2023-12-12 às 17 46 23](https://github.com/platformbuilders/fluid-react/assets/6132299/0613af47-abcd-481c-b5a5-5eed6afc19b5)

## Tipo de mudança 🏗

- [ ] Nova feature (mudança non-breaking que adiciona uma funcionalidade)
- [ ] Bug fix (mudança non-breaking que conserta um problema)
- [X] Refactor (mudança non-breaking que melhora o código)
- [ ] Chore (nenhuma das anteriores, como upgrade de libs)
- [ ] Breaking change 🚨

## Checklist 🧐

- [X] Testado no Yalc
- [X] Testado no Chrome
- [ ] Testado no Safari

2023-12-12 23:42 UTC, ammichael requested changes

2023-12-12 23:42 UTC, ammichael commented on src/components/Button/styles.tsx
> +    box-shadow: 0px 1px 3px 0px rgba(0, 0, 0, 0.1);
@mdlucas esse shadow deveria vir do theme, não? 🤔

2023-12-12 23:42 UTC, ammichael commented on src/components/Button/styles.tsx
> +      background-color: ${colorButton}90;
o hover é algo que não está definido no Fluid, está? se não, puxa o Bruce e bate o martelo com ele no comportamento esperado

2023-12-12 23:42 UTC, ammichael commented on src/components/Button/styles.tsx
> +    case 'outline':
esses `case` estão previstos no Fluid?

2023-12-12 23:42 UTC, ammichael commented on src/components/Button/styles.tsx
> +    font-size: 18px;
e esses `font-size` com px estático? 🕵️

2023-12-12 23:42 UTC, ammichael commented on src/components/Button/styles.tsx
> +  padding: 12px;
🕵️

2023-12-12 23:42 UTC, ammichael commented on src/components/Button/styles.tsx
>    transition: all 0.2s ease-in-out;
outro comportamento que vale já aproveitar e combinar o comportamento no Fluid

2023-12-12 23:42 UTC, ammichael commented on src/components/Button/styles.tsx
> +  font-size: 16px;
pq esses `px` estáticos? aqui e os anteriores 🤔

2023-12-12 23:42 UTC, ammichael commented on src/components/Button/types.ts
> +  | 'info';
essas variants e colors deveriam estar vindo do `theme-toolkit` 🤔

2023-12-12 23:45 UTC, mdlucas commented on src/components/Button/styles.tsx
> +      background-color: ${colorButton}90;
tá sim, no figma tem o hover do botão

2023-12-12 23:46 UTC, mdlucas commented on src/components/Button/styles.tsx
> +    case 'outline':
sim, é assim que está no figma

2023-12-12 23:48 UTC, mdlucas commented on src/components/Button/types.ts
> +  | 'info';
acho que não, as variants são do botão, e não do tema

2023-12-12 23:52 UTC, mdlucas commented on src/components/Button/styles.tsx
> +    box-shadow: 0px 1px 3px 0px rgba(0, 0, 0, 0.1);
nesse caso não, porque é especifico do botão, pelo o que eu entendi o box-shadow que temos no tema é mais relacionado a cards ou niveis de background

2023-12-12 23:54 UTC, mdlucas commented on src/components/Button/styles.tsx
>    transition: all 0.2s ease-in-out;
não entendi

2023-12-12 23:56 UTC, mdlucas commented
@ammichael esse é o figma do Torra, o pessoal de design ta usando esse tipo de nomenclatura para os botões, por isso alterei as varitants, agora temos filled, ghost, tint e outline, cada uma mudando a cor(primary, danger e etc...) de acordo com o que é passado
![Captura de Tela 2023-12-12 às 20 55 07](https://github.com/platformbuilders/fluid-react/assets/6132299/39dcdd65-d506-401e-af9e-b02ef7e45116)

2023-12-13 13:07 UTC, ammichael commented on src/components/Button/styles.tsx
> +    box-shadow: 0px 1px 3px 0px rgba(0, 0, 0, 0.1);
Hmm.. eu penso que isso seria importante ter em alguma variável do Fluid. Vamos deixar assim por enquanto, mas é importante poder adicionar/alterar/remover o shadow de acordo com cada projeto.

2023-12-13 13:08 UTC, ammichael commented on src/components/Button/styles.tsx
>    transition: all 0.2s ease-in-out;
Perdão, faltou mais contexto. Digo o comportamento de animação quando der hover. Sempre será um `ease`?

2023-12-13 13:10 UTC, ammichael commented on src/components/Button/types.ts
> +  | 'info';
Sei que é chato, mas entendo que é parte do necessário isso estar vindo do Toolkit para não ficar desalinhado com a estrutura em si do Fluid

2023-12-13 13:16 UTC, mdlucas commented on src/components/Button/types.ts
> +  | 'info';
é que eu acho estranho ter um componente na lib que é tipado por outra lib

2023-12-13 13:16 UTC, mdlucas commented on src/components/Button/styles.tsx
> +    box-shadow: 0px 1px 3px 0px rgba(0, 0, 0, 0.1);
sim, acho que vamos ter que começar a evoluir o tema para token por componente tambem

2023-12-13 13:32 UTC, fabinppkbuilders reviewed
Mesmo usando yalc eu não consegui utilizar o template-react com esse botão.

Tive que forçadamente instalar a "@radix-ui/react-icons" no template e mesmo assim as variants não funcionaram corretamente.

Ex do botão "ghost":
<img width="214" alt="Captura de Tela 2023-12-13 às 09 30 10" src="https://github.com/platformbuilders/fluid-react/assets/84453168/732dc72b-58bc-4325-bc97-7e165d5d01c6">


Como vc usou o yalc pra testar?

2023-12-13 14:04 UTC, mdlucas commented
> Mesmo usando yalc eu não consegui utilizar o template-react com esse botão.
> 
> Tive que forçadamente instalar a "@radix-ui/react-icons" no template e mesmo assim as variants não funcionaram corretamente.
> 
> Ex do botão "ghost": <img alt="Captura de Tela 2023-12-13 às 09 30 10" width="214" src="https://private-user-images.githubusercontent.com/84453168/290205848-732dc72b-58bc-4325-bc97-7e165d5d01c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NzQ2MzAsIm5iZiI6MTcwMjQ3NDMzMCwicGF0aCI6Ii84NDQ1MzE2OC8yOTAyMDU4NDgtNzMyZGM3MmItNThiYy00MzI1LWJjOTctN2UxNjVkNWQwMWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDEzMzIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjYWEyM2E0Y2EwNjI2NWNiZWMzY2UyZTdhYjNlZDg2YTc3ZWFmMTgzZjQ2ZDlmYmU3MGRiN2U4MDNlMmNiYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yq9uFWJby0gcO55TcedEybBPChCGw3LZ0HiVGs6yx-s">
> 
> Como vc usou o yalc pra testar?

tem mudanças no template tambem, mas so posso abrir o PR depois de gerar a versão aqui
por algum motivo o template estava editando o componente inteiro, o que nao faz sentido, removi as alterações de la pra centralizar tudo na lib
@fabinppkbuilders

2023-12-13 18:31 UTC, mdlucas commented on src/components/Button/types.ts
> +  | 'info';
@ammichael acha melhor deixar esse type no theme-toolkit mesmo ?

2023-12-13 18:46 UTC, fabinppkbuilders reviewed
A falta das props removidas (rounded, hasBorder..) não poderá fazer outros projetos quebrarem? (breaking change)
Assim como a remoção da variant "primary" por exemplo.

Falando por mim, fica bem complicado aprovar algo que eu não consegui validar. Se o PR do template fosse aberto facilitaria mais as coisas. Seria possível?

2023-12-13 18:46 UTC, fabinppkbuilders commented on src/components/Button/styles.tsx
> +  width: ${({ fullWidth }) => (!!fullWidth ? '100%' : undefined)};
essa linha pode virar `width: undefined;`, isso pode ser um problema?

2023-12-13 18:46 UTC, fabinppkbuilders commented on src/components/Button/styles.tsx
> +  gap: 8px;
Esse tamanho fixo não poderá gerar problemas depois?

2023-12-13 18:46 UTC, fabinppkbuilders commented on src/components/Button/index.tsx
> +          <TextButton className="text-button" variant={typographyVariant}>
Por que usar styled-component com className?

2023-12-13 20:06 UTC, mdlucas commented on src/components/Button/styles.tsx
> +  gap: 8px;
não, porque ser alterado via css caso mude o projeto, e nao temos um token especifico no tema para isso

2023-12-13 20:08 UTC, mdlucas commented on src/components/Button/index.tsx
> +          <TextButton className="text-button" variant={typographyVariant}>
acho que são coisas distintas, uma não sobrescreve a outra.
usei a classe para ficar facil alterar o estilo do texto do botao com css quando necessário

2023-12-13 20:09 UTC, mdlucas commented on src/components/Button/styles.tsx
> +  width: ${({ fullWidth }) => (!!fullWidth ? '100%' : undefined)};
acredito que ele fique vazio e nao seta a propriedade, mas vou testar

2023-12-13 20:09 UTC, mdlucas commented
> A falta das props removidas (rounded, hasBorder..) não poderá fazer outros projetos quebrarem? (breaking change) Assim como a remoção da variant "primary" por exemplo.
> 
> Falando por mim, fica bem complicado aprovar algo que eu não consegui validar. Se o PR do template fosse aberto facilitaria mais as coisas. Seria possível?

@fabinppkbuilders 
sim, concordo que é break change, vou abrir o PR no template

2023-12-14 17:47 UTC, luancurti approved these changes

2023-12-14 17:49 UTC, merged

2023-12-14 19:06 UTC, fabinppkbuilders commented
@mdlucas 
Mesmo com a `1.2.0` da fluid-react e com a `0.3.0` da theme-toolkit eu continuei obtendo problemas de tipagem no template-react.

Será que estou fazendo algo errado pra testar ou é preciso algo mais para que essas alterações sejam validadas por completo?

@luancurti como vc validou?